theme: jekyll-theme-minimal
title: Jime Balvin
logo: assets/profile1.png
description: Computer Science Graduate | Aspiring Data Scientist |  Transportation, Logistics & Supply Chain Background | Focused on Operational Data Insights
