theme: jekyll-theme-minimal
title: Jime Balvin
description: Computer Science Graduate | Aspiring Data Scientist |  Transportation, Logistics & Supply Chain Background | Focused on Operational Data Insights
